### ISSUE TITLE
Duplicating an activity results in a broken course

### ISSUE THREAD

**Issue by abias** [andrewhancox/moodle-availability_otherenrolled#3]
Environment:
* Moodle 4.1.5
* Plugin version v1.0.0 (2023042100)

Steps to reproduce:
* Create a course
* Add an arbitrary activity to the course and the 'otherenrolled' activity to this activity
* Go back to the course main page
* Duplicate the activity

Expected result:
* The activity is duplicated
* Each edition has the availability condition set

Actual result:
* The course is broken / inaccessible
* Moodle just shows a fatal error, stating that the course cannot be found in the database anymore.
* Debugging message:
```
Der Datensatz kann nicht in der  Datenbanktabelle course gefunden werden. 
Debug: 
SELECT id,category FROM {course} WHERE id = ?
[array (  0 => 0,)]
Error code: invalidrecord* 
line 1654 of /lib/dml/moodle_database.php: dml_missing_record_exception thrown* 
line 1630 of /lib/dml/moodle_database.php: call to moodle_database->get_record_select()* 
line 7142 of /lib/accesslib.php: call to moodle_database->get_record()* 
line 70 of /availability/condition/otherenrolled/classes/condition.php: call to context_course::instance()* 
line 84 of /availability/classes/condition.php: call to availability_otherenrolled\condition->is_available()* 
line 265 of /availability/classes/tree.php: call to core_availability\condition->check_available()* 
line 197 of /availability/classes/info.php: call to core_availability\tree->check_available()* 
line 2275 of /lib/modinfolib.php: call to core_availability\info->is_available()* 
[...]
```

I haven't looked into the code yet, but I expect that during the activity duplication, a 'otherenrolled' reference to a course ID 0 is added to the duplicated activity instead of a reference to the original course ID.

Fixing it manually:
If you just want to get the broken course up and running again, you can go to your database, run this query:
```
SELECT *  FROM `mdl_course_modules` WHERE `availability` LIKE '%otherenrolled%'
```
and just replace the availability with NULL of the affected activity ID. 
That way, the course can be accessed again and you can set the availability condition in the duplicated activity manually.

**Comment by andrewhancox** [comment]
Fixed (or at least mitigated against)
